models:
  - model: output/OLMoE-1B-7B-0125/math/full_bs-32_lr-2e-5-linear_epochs-2_liger_z2
    parameters:
      density: 0.6
      weight: 0.5
  - model: output/OLMoE-1B-7B-0125/new_ml/full_bs-32_lr-2e-5-linear_epochs-2_liger_z2
    parameters:
      density: 0.6
      weight: 0.5
merge_method: dare_ties
base_model: /mnt/dolphinfs/ssd_pool/docker/user/hadoop-aipnlp/FMG/huangcanbin02/HuggingFace/models/allenai/OLMoE-1B-7B-0125
parameters:
  normalize: true
  int8_mask: true
dtype: bfloat16
tokenizer:
  source: output/OLMoE-1B-7B-0125/math/full_bs-32_lr-2e-5-linear_epochs-2_liger_z2
chat_template: auto

